"""init

Revision ID: e0394fb653b8
Revises: 
Create Date: 2026-01-26 22:34:04.064393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'e0394fb653b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector") #installs the vector extention

    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('exchange_code', sa.Text(), nullable=False),
    sa.Column('security_type', sa.Text(), nullable=False),
    sa.Column('market_sector', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker'),
    sa.UniqueConstraint('ticker', 'exchange_code', name='uq_company_ticker_exchange')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preprocessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('para_structured_text', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('org_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('raw_text_fts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(raw_text, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'content_hash', name='uq_transcripts_hash'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'fiscal_quarter', name='uq_transcripts_period')
    )
    op.create_index('ix_transcripts_fts', 'transcripts', ['raw_text_fts'], unique=False, postgresql_using='gin')
    op.create_table('orgs_in_transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('org_name', sa.Text(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'org_name', name='uq_org_per_transcript')
    )
    op.create_index('ix_org_norm', 'orgs_in_transcripts', ['org_name'], unique=False)
    op.create_index('ix_org_transcript', 'orgs_in_transcripts', ['transcript_id'], unique=False)
    op.create_table('transcript_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'chunk_index', name='uq_chunk_index')
    )
    op.create_index('ix_chunk_transcript', 'transcript_chunks', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_transcript', table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    op.drop_index('ix_org_transcript', table_name='orgs_in_transcripts')
    op.drop_index('ix_org_norm', table_name='orgs_in_transcripts')
    op.drop_table('orgs_in_transcripts')
    op.drop_index('ix_transcripts_fts', table_name='transcripts', postgresql_using='gin')
    op.drop_table('transcripts')
    op.drop_table('companies')
    # ### end Alembic commands ###
